### PR TITLE
Create pages, redesign

### PR DESCRIPTION
**Pull request by kylehalleman**
Opening a PR now before coding just to make intentions known and have a discussion.

## Goals

1. Organize the content into distinct pages.
2. Simplify deploy process so Markdown in repo matches published content on site.
3. Update site design, either by new template or tweaking existing.

## Pages

TBD

## Deploy process

Want to look into having the source repo just be the styling and templates, plus markdown docs. Want to see if we can use Github Actions to make the deploy so built files aren't stored in repo.

## Redesign

Want to further simplify the site design and optimize readability, responsiveness, and performance.

### CODE REVIEW

**Comment by Aycrazy** [comment]
Pages could be divided into "for service providers" and "for those seeking assistance"
Further, within pages, categories of help can be more well defined.  This can be based on sector of the service (either provided or received)

I think what you're mentioning about the deploy process seems pretty straightforward, I've never used Github Actions. Happy to look into it and have a discussion.

On the design side, I think there may be some people we can reach out to that may be interested in helping us with some UI/UX exercises to make the organization more well thought out and the site architecture more suitable for a user who is looking for a specific set of supports.  Maybe we can schedule a meeting to discuss, and invite some people in?

**Comment by Aycrazy** [comment]
An additional page can be made for laypeople who want to help.

###  What I'm currently proposing for pages:

- For service providers
- For those in need of assistance
- For individuals who want to help

**Comment by Aycrazy** [comment]
Food for thought: https://www.covid19italia.help/

**Comment by kylehalleman** [comment]
I think that separation of pages makes sense. I was originally thinking of something else but that gets to the core of it. I'd add a 4th main section that is facts/stats/general information. That could be the landing page, more or less.

I am going to work locally on these changes on the `pages` branch this afternoon. When I get it into a decent state I'll push the changes so we can discuss in this PR.

Thanks for your feedback and thoughts!

**Comment by Aycrazy** [comment]
I think we have what we need re: github actions here :https://github.com/marketplace/actions/jekyll-action.  Perhaps we can use this repo as the template, and mine as the build location?

**Comment by kylehalleman** [comment]
Yeah I looked into that, and I think we might not need Actions after all. I wanted to make sure the Markdown files (including the README) were the source of truth. I have something locally that I'll be pushing up to this branch soon for review.

**Comment by kylehalleman** [comment]
Separating out the links and verifying the links still work.

**Comment by kylehalleman** [comment]
Ok, pushed my updates.

## What's changed

* Simplified the design.
* Added pages
  * General information and data (README.md)
  * How to get help
  * How to help (volunteering and donating opportunities)
  * How to contribute (to this site)
* Each page has a table of contents for easier navigation
* Add list of contributors to the bottom of pages
* Removed information that did not have a source link (see Goals below)

## Goals

1. The primary goal for this site is to be a directory resource for people to find links to official documentation and updates. To keep information that is not directly linkable on this site would mean it would become stale as things evolve. Therefore, I chose to favor links to primary sources for information on specific dates/times/etc.
2. Fast and available. Both from a page load and a legibility perspective, I want users to get to this page and locate what they need ASAP. Thus I removed the default Jekyll theme in favor of a small CSS file from another open-source library I maintain. I also removed the video on the main page as it was breaking responsiveness and pulled in Youtube JavaScript that adds to page bloat.

This PR also adds a gitignore that should clean up the repo to have it minimally store what is needed to render the site.

**Pull request merged**
